DRILL-7911 Increase the max direct memory (#2219)
2500Mb is not enough on Linux ARM64

Fixes errors like:

[ERROR] Tests run: 19, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 5.039 s <<< FAILURE! - in org.apache.drill.exec.record.vector.TestValueVector
[ERROR] org.apache.drill.exec.record.vector.TestValueVector.testFixedVectorReallocation  Time elapsed: 0.037 s  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<org.apache.drill.exec.exception.OversizedAllocationException> but was<org.apache.drill.exec.exception.OutOfMemoryException>
	at org.apache.drill.exec.record.vector.TestValueVector.testFixedVectorReallocation(TestValueVector.java:107)
Caused by: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 2147483644 byte(s) of direct memory (used: 872415232, max: 2621440000)
	at org.apache.drill.exec.record.vector.TestValueVector.testFixedVectorReallocation(TestValueVector.java:107)