Simplify CpuGaugeSet fixing the non-Sun/Oracle code path in the process.
The com.sun.management internal implementation of OperatingSystemMXBean is
used by Drill to report a CPU metric that is not available in the public
interface. Even though code to handle non-Sun/Oracle runtimes for the
OperatingSystemMXBean was present, it would still cause them to attempt to
load a class from com.sun.management causing a NoClassDefFoundError.